"""corrigido FK Historico_Aluno

Revision ID: 08383e5edc35
Revises: 890d4c5ee57e
Create Date: 2023-12-19 20:48:22.401142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08383e5edc35'
down_revision = '890d4c5ee57e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
