"""empty message

Revision ID: 1c9d28c24d07
Revises: 496ae0f16bb5
Create Date: 2023-12-25 18:39:56.214702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c9d28c24d07'
down_revision = '496ae0f16bb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipoinstrumento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('codigo', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tipoinstrumento'))
    )
    op.drop_table('tipo_instrumento')
    with op.batch_alter_table('instrumento', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_instrumento_nome_tipoinstrumento'), 'tipoinstrumento', ['nome'], ['id'])

    with op.batch_alter_table('unidade', schema=None) as batch_op:
        batch_op.alter_column('gestor',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_unidade_gestor_coordenador'), 'coordenador', ['gestor'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unidade', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_unidade_gestor_coordenador'), type_='foreignkey')
        batch_op.alter_column('gestor',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('instrumento', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_instrumento_nome_tipoinstrumento'), type_='foreignkey')
        batch_op.alter_column('nome',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    op.create_table('tipo_instrumento',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=50), nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_tipo_instrumento')
    )
    op.drop_table('tipoinstrumento')
    # ### end Alembic commands ###
