"""alterado coordenador

Revision ID: 222d299e8ee0
Revises: c79c6ce143b7
Create Date: 2023-12-25 09:09:10.779247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '222d299e8ee0'
down_revision = 'c79c6ce143b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_aluno_email'), ['email'])

    with op.batch_alter_table('coordenador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('funcao', sa.String(length=50), nullable=False))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.create_unique_constraint(batch_op.f('uq_coordenador_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_coordenador_telefone'), ['telefone'])

    with op.batch_alter_table('turma', schema=None) as batch_op:
        batch_op.alter_column('coordenador_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turma', schema=None) as batch_op:
        batch_op.alter_column('coordenador_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('coordenador', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_coordenador_telefone'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_coordenador_email'), type_='unique')
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('funcao')

    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_aluno_email'), type_='unique')

    # ### end Alembic commands ###
