"""empty message

Revision ID: 32ef3c8a2a6c
Revises: 1c9d28c24d07
Create Date: 2023-12-25 18:45:14.855656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32ef3c8a2a6c'
down_revision = '1c9d28c24d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coordenador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidade_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_coordenador_unidade_id_unidade'), 'unidade', ['unidade_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coordenador', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_coordenador_unidade_id_unidade'), type_='foreignkey')
        batch_op.drop_column('unidade_id')

    # ### end Alembic commands ###
