"""incluido coluna imagem

Revision ID: 3a64905c76a0
Revises: ef3613d53589
Create Date: 2023-12-23 18:29:01.386513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a64905c76a0'
down_revision = 'ef3613d53589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(length=20), nullable=True))

    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(length=20), nullable=True))

    with op.batch_alter_table('coordenador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coordenador', schema=None) as batch_op:
        batch_op.drop_column('image_file')

    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.drop_column('image_file')

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###
