"""excluido tabela estado instrumento

Revision ID: 3cdcee1a78f6
Revises: 222d299e8ee0
Create Date: 2023-12-25 10:28:47.745923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cdcee1a78f6'
down_revision = '222d299e8ee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_aluno')
    op.drop_table('estadoinstrumento')
    with op.batch_alter_table('instrumento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado_instrumento', sa.String(length=50), nullable=True))
        batch_op.drop_constraint('fk_instrumento_estadoinstrumento_id_estadoinstrumento', type_='foreignkey')
        batch_op.drop_column('estadoinstrumento_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrumento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estadoinstrumento_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_instrumento_estadoinstrumento_id_estadoinstrumento', 'estadoinstrumento', ['estadoinstrumento_id'], ['id'])
        batch_op.drop_column('estado_instrumento')

    op.create_table('estadoinstrumento',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('estado', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_estadoinstrumento')
    )
    op.create_table('_alembic_tmp_aluno',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('telefone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('dataNasc', sa.DATETIME(), nullable=True),
    sa.Column('dataAdmissao', sa.DATETIME(), nullable=True),
    sa.Column('dataDesligamento', sa.DATETIME(), nullable=True),
    sa.Column('nomeResponsavel', sa.VARCHAR(length=50), nullable=True),
    sa.Column('telefoneResponsavel', sa.VARCHAR(length=20), nullable=True),
    sa.Column('emailResponsavel', sa.VARCHAR(length=100), nullable=True),
    sa.Column('anotacoesAluno', sa.VARCHAR(length=400), nullable=True),
    sa.Column('image_file', sa.VARCHAR(length=20), nullable=True),
    sa.Column('turma_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['turma_id'], ['turma.id'], name='fk_aluno_turma_id_turma'),
    sa.PrimaryKeyConstraint('id', name='pk_aluno'),
    sa.UniqueConstraint('email', name='uq_aluno_email')
    )
    # ### end Alembic commands ###
