"""empty message

Revision ID: 496ae0f16bb5
Revises: aacd104abf27
Create Date: 2023-12-25 17:38:35.043376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496ae0f16bb5'
down_revision = 'aacd104abf27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidade_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_aluno_unidade_id_unidade'), 'unidade', ['unidade_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_aluno_unidade_id_unidade'), type_='foreignkey')
        batch_op.drop_column('unidade_id')

    # ### end Alembic commands ###
