"""empty message

Revision ID: 635a62285cc8
Revises: 3cdcee1a78f6
Create Date: 2023-12-25 11:18:12.198583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635a62285cc8'
down_revision = '3cdcee1a78f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_instrumento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('codigo', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tipo_instrumento'))
    )
    with op.batch_alter_table('instrumento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('etiqueta', sa.String(length=5), nullable=False))
        batch_op.add_column(sa.Column('anotacao', sa.String(length=300), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_instrumento_etiqueta'), ['etiqueta'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrumento', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_instrumento_etiqueta'), type_='unique')
        batch_op.drop_column('anotacao')
        batch_op.drop_column('etiqueta')

    op.drop_table('tipo_instrumento')
    # ### end Alembic commands ###
