"""empty message

Revision ID: 76fe6ab87498
Revises: 9fa000ae2081
Create Date: 2023-12-25 17:06:34.836786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76fe6ab87498'
down_revision = '9fa000ae2081'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turma', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instrumento_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_turma_instrumento_id_instrumento'), 'instrumento', ['instrumento_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turma', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_turma_instrumento_id_instrumento'), type_='foreignkey')
        batch_op.drop_column('instrumento_id')

    # ### end Alembic commands ###
