"""include historico_aluno

Revision ID: 890d4c5ee57e
Revises: 
Create Date: 2023-12-19 19:47:47.677426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '890d4c5ee57e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historico_aluno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('dataAdmissao', sa.DateTime(), nullable=True),
    sa.Column('dataDesligamento', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turma.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historico_aluno')
    # ### end Alembic commands ###
