"""empty message

Revision ID: 9fa000ae2081
Revises: 635a62285cc8
Create Date: 2023-12-25 16:11:58.112621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fa000ae2081'
down_revision = '635a62285cc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrumento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dataAquisicao', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrumento', schema=None) as batch_op:
        batch_op.drop_column('dataAquisicao')

    # ### end Alembic commands ###
