"""empty message

Revision ID: a01bb85d4c6c
Revises: 8d376e624030
Create Date: 2023-12-26 11:35:43.282593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a01bb85d4c6c'
down_revision = '8d376e624030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matricula', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aluno_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_matricula_aluno_id_aluno'), 'aluno', ['aluno_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matricula', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_matricula_aluno_id_aluno'), type_='foreignkey')
        batch_op.drop_column('aluno_id')

    # ### end Alembic commands ###
