"""empty message

Revision ID: b67020e22338
Revises: 76fe6ab87498
Create Date: 2023-12-25 17:13:46.341674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b67020e22338'
down_revision = '76fe6ab87498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turma', schema=None) as batch_op:
        batch_op.alter_column('diaSemana',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.DateTime(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turma', schema=None) as batch_op:
        batch_op.alter_column('diaSemana',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
