"""empty message

Revision ID: b741730f01f3
Revises: b67020e22338
Create Date: 2023-12-25 17:17:00.363030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b741730f01f3'
down_revision = 'b67020e22338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turma', schema=None) as batch_op:
        batch_op.alter_column('diaSemana',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('horario',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.DateTime(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turma', schema=None) as batch_op:
        batch_op.alter_column('horario',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=8),
               nullable=False)
        batch_op.alter_column('diaSemana',
               existing_type=sa.String(length=20),
               type_=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
