"""empty message

Revision ID: baaf11e42cc4
Revises: 32ef3c8a2a6c
Create Date: 2023-12-25 18:51:10.377376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baaf11e42cc4'
down_revision = '32ef3c8a2a6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unidade', schema=None) as batch_op:
        batch_op.drop_constraint('fk_unidade_gestor_coordenador', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unidade', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_unidade_gestor_coordenador', 'coordenador', ['gestor'], ['id'])

    # ### end Alembic commands ###
